### ISSUE TITLE
Weather is in Fahrenheit

### ISSUE THREAD

**Issue by halkeye** [FlorianZ/hadashboard#23]
I think this might be a smartthings request, but temp is in Fahrenheit even though location/preferences says Celsius

**Comment by Raphael7777** [comment]
I know this topic is old but I installed the beautiful Hadashboard. What I miss is the api key to compile smartthings.rb. Do I need any sort of sensor to get the SmartWeather tile to working? Can you kindly direct me which sensor do I need?
Thanks to reply

**Comment by bmmiller** [comment]
Hey! It's built-in and just usies your hubs location unless you pick something different. Check out the main.erb file for the example but you do not need a special sensor.

**Comment by Raphael7777** [comment]
But still I need an Hub. It's correct?

**Comment by bmmiller** [comment]
Yes.

**Comment by Raphael7777** [comment]
Bmmiller I installed your hadashboard. But still the weather forecast is not workink . I rebootted Smartthings HUB, changed to C the code and still forecast does not update. Can you suggests what is wrong with me?
![forecast](https://user-images.githubusercontent.com/34964618/52940721-81922f00-3367-11e9-936f-ed00e3a04be1.jpg)

**Comment by bmmiller** [comment]
@Raphael7777 Does it work with Farenheit?  The above workaround for Celsius was never confirmed or tested by me personally.

**Comment by Raphael7777** [comment]
No also in Farenheit  it does not works. I doubt about my Hub now.
Do you have an idea? Should I reinstall?

Anyway with FlorianZ HADashboiard the workaround about celsius was working some months ago

**Comment by bmmiller** [comment]
Other than you not being in the US where this was designed for, no.

Some in Europe have had to use a different link to authorize the app but they get errors right away at the authorize step.

Are you seeing errors there?

**Comment by Raphael7777** [comment]
In http://myapp-name.herokuapp.com/smartthings/authorize I have not errors at all. I'm living in Italy . Are you thinking I need another link to authorize?
I usually log in here: https://graph.api.smartthings.com/

And before that I own an ST UK Hub!

**Comment by Raphael7777** [comment]
I reinstalled all. But got 2 errors : 
1) `Warning: The "HEROKU_" namespace is protected and shouldn't be used`
2) `WARNING:
remote: 
remote:        Removing `Gemfile.lock` because it was generated on Windows.
remote:        Bundler will do a full resolve so native gems are handled properly.
remote:        This may result in unexpected gem versions being used in your app.
remote:        In rare occasions Bundler may not be able to resolve your dependencies at all
![forecast](https://user-images.githubusercontent.com/34964618/53008409-9ccd6f00-3439-11e9-8f52-a18a74826bee.jpg)
`

These errors can be there when I firstly installed but I don't care at that time .
![forecast](https://user-images.githubusercontent.com/34964618/53008444-b8387a00-3439-11e9-8253-2f21aa1f3131.jpg)

**Comment by bmmiller** [comment]
Those aren't errors. Those are warnings and can be ignored for now.

**Comment by Raphael7777** [comment]
I try to reinstall and log in in ST here: https://graph-eu01-euwest1.api.smartthings.com/
This site should be for european. In fact if I look for my Hub there that is not listed. I try then I say what happen.

No joy at all. But what surprise me is when I authorize via ST there is a list of Things to authorize but nothing to flag. Is that correct?

**Comment by Raphael7777** [comment]
I'm a newbie on this but maybe (?) what I read can be one the possibilities because my Dashboard does not show weather forecast::  Weather API changes from 1st January 2019!
in Smartthings:
"The WeatherUnderground (WU) APIs SmartThings has been using to access local weather data are being shut down at the end of this year. This means any Automations or Devices that use the getWeatherFeature() method will stop running or begin returning errors on January 1, 2019.

We are taking steps to ensure that the SmartThings SmartApps and the SmartWeather Station Tile device handler will continue to work by porting them to new APIs from The Weather Company (TWC). These will be released into Production this week and there will be no gap in performance. To maintain your SmartApps and device handlers, we have exposed the following methods for SmartApps and Device Handlers 56 to replace getWeatherFeature".

I'm at the step to migrate to another Dashboard if this is the case. What can you think Bmmiller?

**Comment by bmmiller** [comment]
I mean, maybe, but if this were an issue, I would expect it to not work for anybody.
